### ISSUE TITLE
Query channels should have pagination

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-relayer#20]
due the the relayer not querying all channels (#13) it has been patched with a high pagination limit.
This seems like it's causing the query to timeout (and possibly the hub nodes to get stuck but not necessarily related).
Either way we need to change this query to be paginated.

relevant repeated log from a rollapp operator:|

```
ts=2023-09-20T15:08:29.083208Z lvl=info msg="Failed to query connection channels" conn_id=connection-10158 attempt=1 max_attempts=5 error="rpc error: code = Unknown desc = cannot query with height in the future; please provide a valid height: invalid height"
Error: post failed: Post "http://localhost:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by mtsitrin** [comment]
was fixed on cosmos relayer (https://github.com/cosmos/relayer/pull/1087) and merged to v2.3.0

will cherry pick it to our repo
