### ISSUE TITLE
''Error: more than one transaction returned with query'' error on relayer logs and the ibc transfers not reflecting to the balance.All connectivity checks is normal.

### ISSUE THREAD

**Issue by enyaselessar** [dymensionxyz/dymension-relayer#22]
ts=2023-10-15T08:23:21.821170Z lvl=info msg="No acknowledgements to relay" src_chain_id=froopyland_100-1 src_port_id=transfer dst_chain_id=allaboutme_3227000-1 dst_port_id=transfer
ts=2023-10-15T08:23:24.113332Z lvl=info msg="Added packet to relay message list" sequence=1243 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:25.451315Z lvl=info msg="Added packet to relay message list" sequence=1244 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:26.712542Z lvl=info msg="Added packet to relay message list" sequence=1245 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:27.980245Z lvl=info msg="Added packet to relay message list" sequence=1246 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:29.861844Z lvl=info msg="Added packet to relay message list" sequence=1247 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:31.638641Z lvl=info msg="Added packet to relay message list" sequence=1248 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:34.844689Z lvl=info msg="Added packet to relay message list" sequence=1249 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:36.096662Z lvl=info msg="Added packet to relay message list" sequence=1250 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:37.370821Z lvl=info msg="Added packet to relay message list" sequence=1251 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:38.565216Z lvl=info msg="Added packet to relay message list" sequence=1252 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:39.374626Z lvl=info msg="Failed to relay packet from sequence" src_chain_id=froopyland_100-1 src_channel_id=channel-6200 src_port_id=transfer dst_chain_id=allaboutme_3227000-1 dst_channel_id=channel-0 dst_port_id=transfer channel_order=ORDER_UNORDERED error="more than one transaction returned with query"
Error: more than one transaction returned with query
Failed to execute command: /usr/local/bin/roller_bins/rly tx relay-packets rollapp-hub channel-6200 --home /root/.roller/relayer, err: exit status 1
ts=2023-10-15T08:23:43.260440Z lvl=info msg="No acknowledgements to relay" src_chain_id=allaboutme_3227000-1 src_port_id=transfer dst_chain_id=froopyland_100-1 dst_port_id=transfer
ts=2023-10-15T08:23:43.260497Z lvl=info msg="No acknowledgements to relay" src_chain_id=froopyland_100-1 src_port_id=transfer dst_chain_id=allaboutme_3227000-1 dst_port_id=transfer
ts=2023-10-15T08:23:49.273228Z lvl=info msg="Failed to query connection channels" conn_id=connection-11012 attempt=1 max_attempts=5 error="rpc error: code = Unknown desc = cannot query with height in the future; please provide a valid height: invalid height"
ts=2023-10-15T08:23:55.363142Z lvl=info msg="Added packet to relay message list" sequence=1243 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:56.770374Z lvl=info msg="Added packet to relay message list" sequence=1244 src_chain_id=froopyland_100-1
ts=2023-10-15T08:23:57.011068Z lvl=info msg="No acknowledgements to relay" src_chain_id=allaboutme_3227000-1 src_port_id=transfer dst_chain_id=froopyland_100-1 dst_port_id=transfer
ts=2023-10-15T08:23:57.011069Z lvl=info msg="No acknowledgements to relay" src_chain_id=froopyland_100-1 src_port_id=transfer dst_chain_id=allaboutme_3227000-1 dst_port_id=transfer
ts=2023-10-15T08:23:58.419497Z lvl=info msg="Added packet to relay message list" sequence=1245 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:00.125384Z lvl=info msg="Added packet to relay message list" sequence=1246 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:01.449997Z lvl=info msg="Added packet to relay message list" sequence=1247 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:03.139446Z lvl=info msg="Added packet to relay message list" sequence=1248 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:05.039049Z lvl=info msg="Added packet to relay message list" sequence=1249 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:06.286665Z lvl=info msg="Added packet to relay message list" sequence=1250 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:07.479614Z lvl=info msg="Added packet to relay message list" sequence=1251 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:08.424596Z lvl=info msg="Added packet to relay message list" sequence=1252 src_chain_id=froopyland_100-1
ts=2023-10-15T08:24:09.510303Z lvl=info msg="Failed to relay packet from sequence" src_chain_id=froopyland_100-1 src_channel_id=channel-6200 src_port_id=transfer dst_chain_id=allaboutme_3227000-1 dst_channel_id=channel-0 dst_port_id=transfer channel_order=ORDER_UNORDERED error="more than one transaction returned with query"
Error: more than one transaction returned with query
Failed to execute command: /usr/local/bin/roller_bins/rly tx relay-packets rollapp-hub channel-6200 --home /root/.roller/relayer, err: exit status 1

**Comment by ItayLevyOfficial** [comment]
Hey! Have you done anything special with the rollapp before this error started showing? Or it just came out of nowhere?

**Comment by ToanBm** [comment]
I also encountered this error, have you fixed it yet?

**Comment by enyaselessar** [comment]
it has not fixed yet

**Comment by omritoptix** [comment]
hi @enyaselessar @ToanBm . I believe I see the issue. is this still occurring or has been released?

**Comment by enyaselessar** [comment]
Hi, my issue was not resolved so I created a new rollapp.If you know the solution, you can share it here and help the people who having the same issue.Thanks

**Comment by omritoptix** [comment]
yea. but just to make sure I'd like to debug it so I'll need your relayer config and keys to make it easy on me.
can you please run the following command `tar -cvzf output.tar.gz  ~/.roller/relayer/config  ~/.roller/relayer/keys  ~/.roller/relayer/relayer.log` and send me the result file. 

you can send it over a DM  on discord also if you prefer or upload it and send me the link.

**Comment by omritoptix** [comment]
The issue is that some txs are unexpectedly including events they shouldn't on the IBC level. I believe this is due to our IBC fork. Than this txs are also returning in the query (which expects one tx). A fix will be pushed promptly.
